//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week4.Library.WcfClient.ServiceReferenceLibrary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLibrary.ILibraryService")]
    public interface ILibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/FetchBooks", ReplyAction="http://tempuri.org/ILibraryService/FetchBooksResponse")]
        System.Collections.Generic.List<Week4.Library.Core.Book> FetchBooks();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/FetchBooks", ReplyAction="http://tempuri.org/ILibraryService/FetchBooksResponse")]
        System.IAsyncResult BeginFetchBooks(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Week4.Library.Core.Book> EndFetchBooks(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CreateBook", ReplyAction="http://tempuri.org/ILibraryService/CreateBookResponse")]
        bool CreateBook(Week4.Library.Core.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/CreateBook", ReplyAction="http://tempuri.org/ILibraryService/CreateBookResponse")]
        System.IAsyncResult BeginCreateBook(Week4.Library.Core.Book newBook, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateBook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/EditBook", ReplyAction="http://tempuri.org/ILibraryService/EditBookResponse")]
        bool EditBook([System.ServiceModel.MessageParameterAttribute(Name="editBook")] Week4.Library.Core.Book editBook1);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/EditBook", ReplyAction="http://tempuri.org/ILibraryService/EditBookResponse")]
        System.IAsyncResult BeginEditBook(Week4.Library.Core.Book editBook, System.AsyncCallback callback, object asyncState);
        
        bool EndEditBook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeleteBook", ReplyAction="http://tempuri.org/ILibraryService/DeleteBookResponse")]
        bool DeleteBook(int idBook);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/DeleteBook", ReplyAction="http://tempuri.org/ILibraryService/DeleteBookResponse")]
        System.IAsyncResult BeginDeleteBook(int idBook, System.AsyncCallback callback, object asyncState);
        
        bool EndDeleteBook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/FetchPrestiti", ReplyAction="http://tempuri.org/ILibraryService/FetchPrestitiResponse")]
        System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> FetchPrestiti();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/FetchPrestiti", ReplyAction="http://tempuri.org/ILibraryService/FetchPrestitiResponse")]
        System.IAsyncResult BeginFetchPrestiti(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> EndFetchPrestiti(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CreatePrestito", ReplyAction="http://tempuri.org/ILibraryService/CreatePrestitoResponse")]
        bool CreatePrestito(Week4.Library.Core.Models.Prestito newPrestito);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/CreatePrestito", ReplyAction="http://tempuri.org/ILibraryService/CreatePrestitoResponse")]
        System.IAsyncResult BeginCreatePrestito(Week4.Library.Core.Models.Prestito newPrestito, System.AsyncCallback callback, object asyncState);
        
        bool EndCreatePrestito(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/EditPrestito", ReplyAction="http://tempuri.org/ILibraryService/EditPrestitoResponse")]
        bool EditPrestito(Week4.Library.Core.Models.Prestito newPrestito);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/EditPrestito", ReplyAction="http://tempuri.org/ILibraryService/EditPrestitoResponse")]
        System.IAsyncResult BeginEditPrestito(Week4.Library.Core.Models.Prestito newPrestito, System.AsyncCallback callback, object asyncState);
        
        bool EndEditPrestito(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeletePrestito", ReplyAction="http://tempuri.org/ILibraryService/DeletePrestitoResponse")]
        bool DeletePrestito(int idPrestito);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILibraryService/DeletePrestito", ReplyAction="http://tempuri.org/ILibraryService/DeletePrestitoResponse")]
        System.IAsyncResult BeginDeletePrestito(int idPrestito, System.AsyncCallback callback, object asyncState);
        
        bool EndDeletePrestito(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : Week4.Library.WcfClient.ServiceReferenceLibrary.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FetchBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FetchBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Week4.Library.Core.Book> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Week4.Library.Core.Book>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EditBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FetchPrestitiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FetchPrestitiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Week4.Library.Core.Models.Prestito>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreatePrestitoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreatePrestitoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditPrestitoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EditPrestitoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeletePrestitoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeletePrestitoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<Week4.Library.WcfClient.ServiceReferenceLibrary.ILibraryService>, Week4.Library.WcfClient.ServiceReferenceLibrary.ILibraryService {
        
        private BeginOperationDelegate onBeginFetchBooksDelegate;
        
        private EndOperationDelegate onEndFetchBooksDelegate;
        
        private System.Threading.SendOrPostCallback onFetchBooksCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateBookDelegate;
        
        private EndOperationDelegate onEndCreateBookDelegate;
        
        private System.Threading.SendOrPostCallback onCreateBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditBookDelegate;
        
        private EndOperationDelegate onEndEditBookDelegate;
        
        private System.Threading.SendOrPostCallback onEditBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteBookDelegate;
        
        private EndOperationDelegate onEndDeleteBookDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginFetchPrestitiDelegate;
        
        private EndOperationDelegate onEndFetchPrestitiDelegate;
        
        private System.Threading.SendOrPostCallback onFetchPrestitiCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreatePrestitoDelegate;
        
        private EndOperationDelegate onEndCreatePrestitoDelegate;
        
        private System.Threading.SendOrPostCallback onCreatePrestitoCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditPrestitoDelegate;
        
        private EndOperationDelegate onEndEditPrestitoDelegate;
        
        private System.Threading.SendOrPostCallback onEditPrestitoCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeletePrestitoDelegate;
        
        private EndOperationDelegate onEndDeletePrestitoDelegate;
        
        private System.Threading.SendOrPostCallback onDeletePrestitoCompletedDelegate;
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<FetchBooksCompletedEventArgs> FetchBooksCompleted;
        
        public event System.EventHandler<CreateBookCompletedEventArgs> CreateBookCompleted;
        
        public event System.EventHandler<EditBookCompletedEventArgs> EditBookCompleted;
        
        public event System.EventHandler<DeleteBookCompletedEventArgs> DeleteBookCompleted;
        
        public event System.EventHandler<FetchPrestitiCompletedEventArgs> FetchPrestitiCompleted;
        
        public event System.EventHandler<CreatePrestitoCompletedEventArgs> CreatePrestitoCompleted;
        
        public event System.EventHandler<EditPrestitoCompletedEventArgs> EditPrestitoCompleted;
        
        public event System.EventHandler<DeletePrestitoCompletedEventArgs> DeletePrestitoCompleted;
        
        public System.Collections.Generic.List<Week4.Library.Core.Book> FetchBooks() {
            return base.Channel.FetchBooks();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFetchBooks(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFetchBooks(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<Week4.Library.Core.Book> EndFetchBooks(System.IAsyncResult result) {
            return base.Channel.EndFetchBooks(result);
        }
        
        private System.IAsyncResult OnBeginFetchBooks(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginFetchBooks(callback, asyncState);
        }
        
        private object[] OnEndFetchBooks(System.IAsyncResult result) {
            System.Collections.Generic.List<Week4.Library.Core.Book> retVal = this.EndFetchBooks(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFetchBooksCompleted(object state) {
            if ((this.FetchBooksCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FetchBooksCompleted(this, new FetchBooksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FetchBooksAsync() {
            this.FetchBooksAsync(null);
        }
        
        public void FetchBooksAsync(object userState) {
            if ((this.onBeginFetchBooksDelegate == null)) {
                this.onBeginFetchBooksDelegate = new BeginOperationDelegate(this.OnBeginFetchBooks);
            }
            if ((this.onEndFetchBooksDelegate == null)) {
                this.onEndFetchBooksDelegate = new EndOperationDelegate(this.OnEndFetchBooks);
            }
            if ((this.onFetchBooksCompletedDelegate == null)) {
                this.onFetchBooksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFetchBooksCompleted);
            }
            base.InvokeAsync(this.onBeginFetchBooksDelegate, null, this.onEndFetchBooksDelegate, this.onFetchBooksCompletedDelegate, userState);
        }
        
        public bool CreateBook(Week4.Library.Core.Book newBook) {
            return base.Channel.CreateBook(newBook);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateBook(Week4.Library.Core.Book newBook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateBook(newBook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCreateBook(System.IAsyncResult result) {
            return base.Channel.EndCreateBook(result);
        }
        
        private System.IAsyncResult OnBeginCreateBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Week4.Library.Core.Book newBook = ((Week4.Library.Core.Book)(inValues[0]));
            return this.BeginCreateBook(newBook, callback, asyncState);
        }
        
        private object[] OnEndCreateBook(System.IAsyncResult result) {
            bool retVal = this.EndCreateBook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateBookCompleted(object state) {
            if ((this.CreateBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateBookCompleted(this, new CreateBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateBookAsync(Week4.Library.Core.Book newBook) {
            this.CreateBookAsync(newBook, null);
        }
        
        public void CreateBookAsync(Week4.Library.Core.Book newBook, object userState) {
            if ((this.onBeginCreateBookDelegate == null)) {
                this.onBeginCreateBookDelegate = new BeginOperationDelegate(this.OnBeginCreateBook);
            }
            if ((this.onEndCreateBookDelegate == null)) {
                this.onEndCreateBookDelegate = new EndOperationDelegate(this.OnEndCreateBook);
            }
            if ((this.onCreateBookCompletedDelegate == null)) {
                this.onCreateBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateBookCompleted);
            }
            base.InvokeAsync(this.onBeginCreateBookDelegate, new object[] {
                        newBook}, this.onEndCreateBookDelegate, this.onCreateBookCompletedDelegate, userState);
        }
        
        public bool EditBook(Week4.Library.Core.Book editBook1) {
            return base.Channel.EditBook(editBook1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEditBook(Week4.Library.Core.Book editBook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditBook(editBook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndEditBook(System.IAsyncResult result) {
            return base.Channel.EndEditBook(result);
        }
        
        private System.IAsyncResult OnBeginEditBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Week4.Library.Core.Book editBook = ((Week4.Library.Core.Book)(inValues[0]));
            return this.BeginEditBook(editBook, callback, asyncState);
        }
        
        private object[] OnEndEditBook(System.IAsyncResult result) {
            bool retVal = this.EndEditBook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEditBookCompleted(object state) {
            if ((this.EditBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditBookCompleted(this, new EditBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditBookAsync(Week4.Library.Core.Book editBook) {
            this.EditBookAsync(editBook, null);
        }
        
        public void EditBookAsync(Week4.Library.Core.Book editBook, object userState) {
            if ((this.onBeginEditBookDelegate == null)) {
                this.onBeginEditBookDelegate = new BeginOperationDelegate(this.OnBeginEditBook);
            }
            if ((this.onEndEditBookDelegate == null)) {
                this.onEndEditBookDelegate = new EndOperationDelegate(this.OnEndEditBook);
            }
            if ((this.onEditBookCompletedDelegate == null)) {
                this.onEditBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditBookCompleted);
            }
            base.InvokeAsync(this.onBeginEditBookDelegate, new object[] {
                        editBook}, this.onEndEditBookDelegate, this.onEditBookCompletedDelegate, userState);
        }
        
        public bool DeleteBook(int idBook) {
            return base.Channel.DeleteBook(idBook);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteBook(int idBook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteBook(idBook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndDeleteBook(System.IAsyncResult result) {
            return base.Channel.EndDeleteBook(result);
        }
        
        private System.IAsyncResult OnBeginDeleteBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idBook = ((int)(inValues[0]));
            return this.BeginDeleteBook(idBook, callback, asyncState);
        }
        
        private object[] OnEndDeleteBook(System.IAsyncResult result) {
            bool retVal = this.EndDeleteBook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteBookCompleted(object state) {
            if ((this.DeleteBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteBookCompleted(this, new DeleteBookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteBookAsync(int idBook) {
            this.DeleteBookAsync(idBook, null);
        }
        
        public void DeleteBookAsync(int idBook, object userState) {
            if ((this.onBeginDeleteBookDelegate == null)) {
                this.onBeginDeleteBookDelegate = new BeginOperationDelegate(this.OnBeginDeleteBook);
            }
            if ((this.onEndDeleteBookDelegate == null)) {
                this.onEndDeleteBookDelegate = new EndOperationDelegate(this.OnEndDeleteBook);
            }
            if ((this.onDeleteBookCompletedDelegate == null)) {
                this.onDeleteBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteBookCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteBookDelegate, new object[] {
                        idBook}, this.onEndDeleteBookDelegate, this.onDeleteBookCompletedDelegate, userState);
        }
        
        public System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> FetchPrestiti() {
            return base.Channel.FetchPrestiti();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFetchPrestiti(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFetchPrestiti(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> EndFetchPrestiti(System.IAsyncResult result) {
            return base.Channel.EndFetchPrestiti(result);
        }
        
        private System.IAsyncResult OnBeginFetchPrestiti(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginFetchPrestiti(callback, asyncState);
        }
        
        private object[] OnEndFetchPrestiti(System.IAsyncResult result) {
            System.Collections.Generic.List<Week4.Library.Core.Models.Prestito> retVal = this.EndFetchPrestiti(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFetchPrestitiCompleted(object state) {
            if ((this.FetchPrestitiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FetchPrestitiCompleted(this, new FetchPrestitiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FetchPrestitiAsync() {
            this.FetchPrestitiAsync(null);
        }
        
        public void FetchPrestitiAsync(object userState) {
            if ((this.onBeginFetchPrestitiDelegate == null)) {
                this.onBeginFetchPrestitiDelegate = new BeginOperationDelegate(this.OnBeginFetchPrestiti);
            }
            if ((this.onEndFetchPrestitiDelegate == null)) {
                this.onEndFetchPrestitiDelegate = new EndOperationDelegate(this.OnEndFetchPrestiti);
            }
            if ((this.onFetchPrestitiCompletedDelegate == null)) {
                this.onFetchPrestitiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFetchPrestitiCompleted);
            }
            base.InvokeAsync(this.onBeginFetchPrestitiDelegate, null, this.onEndFetchPrestitiDelegate, this.onFetchPrestitiCompletedDelegate, userState);
        }
        
        public bool CreatePrestito(Week4.Library.Core.Models.Prestito newPrestito) {
            return base.Channel.CreatePrestito(newPrestito);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreatePrestito(Week4.Library.Core.Models.Prestito newPrestito, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreatePrestito(newPrestito, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCreatePrestito(System.IAsyncResult result) {
            return base.Channel.EndCreatePrestito(result);
        }
        
        private System.IAsyncResult OnBeginCreatePrestito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Week4.Library.Core.Models.Prestito newPrestito = ((Week4.Library.Core.Models.Prestito)(inValues[0]));
            return this.BeginCreatePrestito(newPrestito, callback, asyncState);
        }
        
        private object[] OnEndCreatePrestito(System.IAsyncResult result) {
            bool retVal = this.EndCreatePrestito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreatePrestitoCompleted(object state) {
            if ((this.CreatePrestitoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreatePrestitoCompleted(this, new CreatePrestitoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreatePrestitoAsync(Week4.Library.Core.Models.Prestito newPrestito) {
            this.CreatePrestitoAsync(newPrestito, null);
        }
        
        public void CreatePrestitoAsync(Week4.Library.Core.Models.Prestito newPrestito, object userState) {
            if ((this.onBeginCreatePrestitoDelegate == null)) {
                this.onBeginCreatePrestitoDelegate = new BeginOperationDelegate(this.OnBeginCreatePrestito);
            }
            if ((this.onEndCreatePrestitoDelegate == null)) {
                this.onEndCreatePrestitoDelegate = new EndOperationDelegate(this.OnEndCreatePrestito);
            }
            if ((this.onCreatePrestitoCompletedDelegate == null)) {
                this.onCreatePrestitoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreatePrestitoCompleted);
            }
            base.InvokeAsync(this.onBeginCreatePrestitoDelegate, new object[] {
                        newPrestito}, this.onEndCreatePrestitoDelegate, this.onCreatePrestitoCompletedDelegate, userState);
        }
        
        public bool EditPrestito(Week4.Library.Core.Models.Prestito newPrestito) {
            return base.Channel.EditPrestito(newPrestito);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEditPrestito(Week4.Library.Core.Models.Prestito newPrestito, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditPrestito(newPrestito, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndEditPrestito(System.IAsyncResult result) {
            return base.Channel.EndEditPrestito(result);
        }
        
        private System.IAsyncResult OnBeginEditPrestito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Week4.Library.Core.Models.Prestito newPrestito = ((Week4.Library.Core.Models.Prestito)(inValues[0]));
            return this.BeginEditPrestito(newPrestito, callback, asyncState);
        }
        
        private object[] OnEndEditPrestito(System.IAsyncResult result) {
            bool retVal = this.EndEditPrestito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEditPrestitoCompleted(object state) {
            if ((this.EditPrestitoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditPrestitoCompleted(this, new EditPrestitoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditPrestitoAsync(Week4.Library.Core.Models.Prestito newPrestito) {
            this.EditPrestitoAsync(newPrestito, null);
        }
        
        public void EditPrestitoAsync(Week4.Library.Core.Models.Prestito newPrestito, object userState) {
            if ((this.onBeginEditPrestitoDelegate == null)) {
                this.onBeginEditPrestitoDelegate = new BeginOperationDelegate(this.OnBeginEditPrestito);
            }
            if ((this.onEndEditPrestitoDelegate == null)) {
                this.onEndEditPrestitoDelegate = new EndOperationDelegate(this.OnEndEditPrestito);
            }
            if ((this.onEditPrestitoCompletedDelegate == null)) {
                this.onEditPrestitoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditPrestitoCompleted);
            }
            base.InvokeAsync(this.onBeginEditPrestitoDelegate, new object[] {
                        newPrestito}, this.onEndEditPrestitoDelegate, this.onEditPrestitoCompletedDelegate, userState);
        }
        
        public bool DeletePrestito(int idPrestito) {
            return base.Channel.DeletePrestito(idPrestito);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeletePrestito(int idPrestito, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeletePrestito(idPrestito, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndDeletePrestito(System.IAsyncResult result) {
            return base.Channel.EndDeletePrestito(result);
        }
        
        private System.IAsyncResult OnBeginDeletePrestito(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idPrestito = ((int)(inValues[0]));
            return this.BeginDeletePrestito(idPrestito, callback, asyncState);
        }
        
        private object[] OnEndDeletePrestito(System.IAsyncResult result) {
            bool retVal = this.EndDeletePrestito(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeletePrestitoCompleted(object state) {
            if ((this.DeletePrestitoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeletePrestitoCompleted(this, new DeletePrestitoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeletePrestitoAsync(int idPrestito) {
            this.DeletePrestitoAsync(idPrestito, null);
        }
        
        public void DeletePrestitoAsync(int idPrestito, object userState) {
            if ((this.onBeginDeletePrestitoDelegate == null)) {
                this.onBeginDeletePrestitoDelegate = new BeginOperationDelegate(this.OnBeginDeletePrestito);
            }
            if ((this.onEndDeletePrestitoDelegate == null)) {
                this.onEndDeletePrestitoDelegate = new EndOperationDelegate(this.OnEndDeletePrestito);
            }
            if ((this.onDeletePrestitoCompletedDelegate == null)) {
                this.onDeletePrestitoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeletePrestitoCompleted);
            }
            base.InvokeAsync(this.onBeginDeletePrestitoDelegate, new object[] {
                        idPrestito}, this.onEndDeletePrestitoDelegate, this.onDeletePrestitoCompletedDelegate, userState);
        }
    }
}
